BranniganLab/density_threshold_affinity

python/DTA/enrichment_plotters.py
python/preliminaries.ipynb

Now works for the new filename format.
!!! NOT BACKWARD COMPATIBLE
REMOVE ALL ```.dat.``` from the middle of file names, if present.
Addressing issue #28

HOTFIX: Fix preliminaries filename parser

---

TCL/helpers/BinTools.tcl
TCL/polarDensity_for_DTA.tcl

Resolves issue #55 : using the center_and_align option will now center your protein at the origin, regardless of whether you are using qwrap or pbc wrap. Also, I cleaned up the code a little.
Tested the code on a toy system; desired results achieved without errors.

55 fix center and align

---

TCL/polarDensity_for_DTA.tcl

leaflet sorter 2 now takes a reference selection (specified in the config file) to compare against, rather than just using z=0 as the yardstick to sort by.

65 leaflet sorter 2 should be more flexible

---

accessible_area/do_get_counts.tcl

do_get_counts will no longer crash, now that the leaflet_sorter is correctly named.

renamed leaflet sorter

---

.github/PULL_REQUEST_TEMPLATE.md
python/density.py

I copy/pasted the new density-related functions into a file called density.py. I have also attached a file to this PR for testing purposes called 'density_test1.ipynb'.
This change streamlines the computation of counts, density, and enrichment.
[density_test1.zip](https://github.com/user-attachments/files/17704403/density_test1.zip)

density.py contains all new density-related procs

---

python/plotting.py
python/preliminaries.ipynb

This fixes a Warning from matplotlib and replaces a code block in the notebook with a one-line function call. Plotting.py is now a file that will continue to grow as we add PRs.
No user-impacting changes (other than the user no longer gets a Warning and the user sees slightly less unecessary code)
[cmap_test.zip](https://github.com/user-attachments/files/17707796/cmap_test.zip)

22 get cmap is deprecated in matplotlib

---

TCL/polarDensity_for_DTA.tcl

When local_midplane2 is run (leaflet_sorter_3), it has trouble at the borders of the box because it doesn't use pbwithin. Now it does use pbwithin and we no longer get intermittent errors when leaflet sorting.
None

92 leaflet sorter 3 fails when lipids split across pb

---

python/Site.py
python/Symmetric_Site.py
python/density.py
python/plotting.py
python/utils.py

This PR implements two classes: Site (Site.py) and Symmetric_Site (Symmetric_Site.py). It also includes all utility functions necessary (utils.py) and plotting functions necessary (plotting.py) to completely replicate the existing machinery for DTA. It also includes a testing notebook, which will create a symmetric site the old way, a Symmetric_Site the new way, and compare all plots and the resulting delta G. The only thing this won't test is the determination of the accessible area.
This PR does not change the user experience in any way but adds all the functionality we will need to change the user experience in the future.
[Site_testing.zip](https://github.com/user-attachments/files/17777607/Site_testing.zip)

New site class testing

---

python/DTA/site_distributions.py

Sites that were only one theta bin wide caused outline_site to fail because dtheta was being determined on the fly by outline_site without sufficient information to determine dtheta in the case that only one theta bin was provided. Now, dtheta is an attribute of the site that gets set by create_simple_site and gets accessed by outline_site.
None
[single-bin-test.zip](https://github.com/user-attachments/files/17818200/single-bin-test.zip)

site now has a dtheta attribute

---

python/preliminaries.ipynb

This PR fixes a figure issue in the Preliminaries notebook. When plotting the density enrichment heatmap, the colorbar would often be cutoff (see issue #106). This is fixed with a bbox_inches='tight' argument.
None

fixed colorbar getting cut off

---

accessible_area/do_get_counts.tcl

do_get_counts.tcl was set up to take a list of lipid names, but can't actually do anything with that list and raises an error instead. I have fixed it.
The $spp variable will now be properly iterated through.

113 do get counts should analyze all species in species list

---

TCL/polarDensity_for_DTA.tcl

When running polarDensityBin the leaflet sorter would run on all lipids in the system, even those outside of the zone of analysis. After this PR, the user can select whether leaflet sorting will only occur for lipids within Rmax or for all lipids. 
In the process, we discovered a bug (issue #104). If the user specified an Rmax that was evenly divisible by dr, then polarDensityBin would analyze past Rmax by one shell. If the user specified an Rmax that was not evenly divisible by dr, then polarDensityBin would happily accept that choice without balking (but density enrichment analysis would be affected in the outermost shell downstream). 
We also found that expected density was being measured on start_frame rather than end_frame (issue #107).
We also found a minor error when no lipids are …

Leaflet sorter speed up and shell selection bug fix

---

python/SymmetricSite.py
python/plotting.py

In the current state, plotting.outline_site would outline each bin individually rather than outline the entire site. This has been fixed. 
Please note that there is no site definition checking in place, so the user is free to define non-contiguous sites, define sites outside of the zone of analysis, define overlapping sites, etc. This is addressed by issue #109 and a future PR.
SymmetricSite now has a bin_coords property, just like Site.

126 site outline contains individual bin edges

---

python/plotting.py

Adds a plot_titration_curve function. Also, outline_site will no longer draw a line at theta=0 when it's not supposed to.

128a generate titration curves from deltag

---

python/plotting.py

Axis spines no longer present in heatmap plots. (They had been showing up in all but the last heatmap, making the plots look funny). 
Additionally, there is now an extra default color added to helix plotting so that GPCRs work by default.

Remove axis spines from heatmap plots

---

TCL/polarDensity_for_DTA.tcl

Leaflet_sorter_2 can either take a reference selection to calculate its height cutoff, or it will default to z=0. The warning that it was defaulting to 0 would display every time leaflet_sorter_2 was invoked IE once for every lipid in the selection area. This was overwhelming and unhelpful. It now displays once at the beginning, which is both whelming and helpful.
Also: in the event that the leaflet sorter option supplied by the user was unrecognized, the code promised to default to leaflet_sorter_1 but then never kept its promise. It now actually invokes leaflet_sorter_1. It also only offers this warning once, as opposed to on every single lipid.
No parameter changes.

138 moved warnings to correct level

---

TCL/polarDensity_for_DTA.tcl
python/density.py

This PR allows the user to specify full atomselection text in their config file rather than limit them to only selecting resnames. Consequently, the variable $lipidbeads_selstr is removed. 
It also introduces the $filenames variable, which stores the names associated with each of the supplied atomselections.
It also removes the calculation of average acyl chain length and the variable $acylchain_selstr. 
User now sets $atomsels and $filename_stems in the config file. User no longer sets $lipids, $lipidbeads_selstrs, and $acylchain_selstrs in the config file.

145 polardensitybin should take atomselection text rather than resnames only

---

TCL/polarDensity_for_DTA.tcl

If a user gave leaflet_sorter_0 multiple head or tail names it would not know what to do with them and error out. It now takes the mean height of any selection that matches what the user provides.
User now needs to specify full atomselection text rather than just a bead name if they are choosing to use leaflet_sorter_0. IE user now needs to specify 'name PO4' instead of just 'PO4' for the $headnames variable in their config file.

leaflet_sorter_0 should take average of head or tail z

---

accessible_area/do_get_counts.tcl

do_get_counts.tcl was trying to use a global variable that is only available in polarDensityBin. It now uses what it has.
None.

fixed params bug

---

TCL/polarDensity_for_DTA.tcl

We need a leaflet sorting option that just assigns all lipids to one leaflet. This is now implemented.
User may now specify leaflet_sorter_option 4, if they wish.

168 need way to assign all lipids to one leaflet

---

TCL/polarDensity_for_DTA.tcl

Theta bin indices were already being saved to the user field. Now radial bin indices are saved to user3 as well.
None.

170 need way to assign bin numbers to user field
